#!/usr/bin/env python3
"""
Extract component and variant data from Figma design context output.
This script parses the React code generated by Figma to extract:
- Component names
- Variant mappings (Fill + Style combinations)
- SVG image URLs
"""

import re
import json
import sys

def extract_component_data(figma_code):
    """Extract component data from Figma-generated React code."""
    components = {}
    
    # Pattern to match component function definitions
    component_pattern = r'type\s+(\w+)Props\s*=\s*\{[^}]*\};\s*function\s+(\w+)\s*\([^)]*\)\s*\{'
    
    # Find all components
    component_matches = list(re.finditer(component_pattern, figma_code, re.MULTILINE))
    
    for match in component_matches:
        component_name = match.group(2)
        if component_name == 'Column':  # Skip the container
            continue
            
        # Extract all imgVector references and their usage
        # Find the function body
        func_start = match.end()
        # Find the closing brace of the function (simplified)
        next_func = figma_code.find('type ', func_start)
        if next_func == -1:
            func_body = figma_code[func_start:]
        else:
            func_body = figma_code[func_start:next_func]
        
        # Extract variant mappings
        variants = {}
        
        # Pattern to match if statements with fill and style
        variant_pattern = r'if\s*\(fill\s*===\s*"(\w+)"\s*&&\s*style\s*===\s*"(\w+)"\)'
        variant_matches = re.finditer(variant_pattern, func_body)
        
        for var_match in variant_matches:
            fill = var_match.group(1)
            style = var_match.group(2)
            
            # Find the imgVector used in this variant
            # Look for imgVector references after this if statement
            variant_start = var_match.end()
            variant_end = func_body.find('if ', variant_start)
            if variant_end == -1:
                variant_end = func_body.find('return', variant_start)
            
            variant_code = func_body[variant_start:variant_end]
            
            # Find imgVector reference
            img_vector_match = re.search(r'imgVector(\d+)', variant_code)
            if img_vector_match:
                vector_index = img_vector_match.group(1)
                # Find the corresponding URL
                url_pattern = rf'const\s+imgVector{vector_index}\s*=\s*"([^"]+)"'
                url_match = re.search(url_pattern, figma_code)
                if url_match:
                    url = url_match.group(1)
                    variant_key = f'{fill}-{style}'
                    variants[variant_key] = url
        
        if variants:
            components[component_name] = {
                'metadata': {'name': component_name},
                'variants': variants
            }
    
    return components

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python extract-figma-data.py <figma-code-file>")
        sys.exit(1)
    
    with open(sys.argv[1], 'r') as f:
        figma_code = f.read()
    
    components = extract_component_data(figma_code)
    
    print(json.dumps(components, indent=2))

